-bash: pushd: run: No such file or directory
/home/limblab/miniconda3/envs/rt/lib/python3.8/runpy.py:126: RuntimeWarning: 'brand.tools' found in sys.modules after import of package 'brand', but prior to execution of 'brand.tools'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/home/limblab/miniconda3/envs/rt/lib/python3.8/runpy.py:126: RuntimeWarning: 'brand.tools' found in sys.modules after import of package 'brand', but prior to execution of 'brand.tools'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/home/limblab/miniconda3/envs/rt/lib/python3.8/runpy.py:126: RuntimeWarning: 'brand.tools' found in sys.modules after import of package 'brand', but prior to execution of 'brand.tools'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
